### ISSUE TITLE
Fix user dashboard rebook and cancel not refetching

### ISSUE THREAD

**Issue by BaoGeist** [McMaster-Engineering-Society/MES-Website-App-Router#462]
This issue will involve looking at the cached keys from the useMakeBooking hook and useCancelBooking hook and making sure it invalidates the right keys after cancelling to trigger a refetch.

Video to reproduce
https://www.awesomescreenshot.com/video/33223794?key=723952971c9e13e932251f131caf24b8

**Comment by shivyam** [comment]
Already done by Gary.
